### ISSUE TITLE
[1.15pre2] dead method

### ISSUE THREAD

**Issue by Yoghurt4C** [vini2003/Buffer#6]
```
[03:35:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net/minecraft/class_1271.<init>(Lnet/minecraft/class_1269;Ljava/lang/Object;Z)V (loaded from file:/C:/Users/yoghu_000/Desktop/modding%20shit/MultiMC/instances/fabric_christmas/.minecraft/.fabric/remappedJars/minecraft-1.15-rc.2/intermediary-minecraft-1.15-pre2-client.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@6a966b43) called from class buffer.item.BufferItem (loaded from file:/C:/Users/yoghu_000/Desktop/modding%20shit/MultiMC/instances/fabric_christmas/.minecraft/mods/buffer-19w38b-1.2.0.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@6a966b43).
	at buffer.item.BufferItem.method_7836(BufferItem.java:108) ~[buffer-19w38b-1.2.0.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:206) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:278) ~[intermediary-minecraft-1.15-pre2-client.jar:?]
```

**Comment by vini2003** [comment]
The 1.15 release might as well be archived. It's extremely early and completely different from 1.14; so yeah, it's awful.

**Comment by vini2003** [comment]
In other words, it's old code, the only support version is 1.14 for now. I originally wrote this for 1.15 then backported and stopped supporting 1.15.
